Repository WOPH96/SSD_Project, pull requests merged in 2024-09, with the labels that each got.

#3 README 변수명 수정했습니다.
  123
  README.md
Labels: documentation

#4 동수
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  README.md
  hello
  hello.cpp
Labels: documentation

#9 코딩 컨벤션 설정 완료
  README.md
Labels: documentation, enhancement

#10 Dongsu
  .vscode/settings.json
  memory.bin
Labels: enhancement

#16 dongsu
  .vscode/settings.json
  memory/memory.bin
  result.txt
Labels: enhancement

#17 세부규정 추가
  README.md
Labels: documentation

#23 파일 입출력 & 메모리 접근 및 제어 코드 작성 완료
  .vscode/settings.json
  memory/data.bin
  memory/memory.bin
  memory/nand.txt
  result/result.txt
  source/Ctrl_SSD.cpp
  source/SSD
Labels: enhancement

#24 test_shell생성
  source/ssd_program
  source/test_shell
  source/test_shell.cpp
Labels: enhancement

#27 함수이름 수정 및 init함수 추가
  source/test_shell
  source/test_shell.cpp
Labels: enhancement

#32 수정완료
  source/SSD
  source/ssd_program
  source/test_shell
  source/test_shell.cpp
Labels: enhancement

#37 TestApp1 및 TestApp2 수정 사항 반영
  source/Shell/shell_func.cpp
Labels: enhancement

#40 testapp1,2 수정
  source/Shell/shell_func.cpp
Labels: enhancement
